import type { FortuneCategory, FortuneContentDefinition } from "./types";

export const FORTUNE_CATEGORY_LABELS = {
  work: "工作",
  learning: "学习",
  health: "健康",
  social: "社交",
  home: "居家",
  outdoors: "户外",
  creativity: "创作",
  entertainment: "娱乐",
} as const satisfies Record<FortuneCategory, string>;

export const FORTUNE_CONTENT = [
  {
    id: "plan-the-day",
    category: "work",
    name: "规划日程",
    good: ["轻重缓急一眼分明", "今天的安排留有呼吸感"],
    bad: ["计划排得太满反而寸步难行", "临时变化会打乱精密时间表"],
  },
  {
    id: "report-progress",
    category: "work",
    name: "汇报进展",
    good: ["重点清楚，问题也有解法", "准备的数据会替你说话"],
    bad: ["细节没对齐容易答非所问", "过度包装会掩盖真正风险"],
  },
  {
    id: "clear-inbox",
    category: "work",
    name: "清理收件箱",
    good: ["积压事项会迅速见底", "一封关键回复能推进全局"],
    bad: ["容易把重要邮件误判成噪音", "回复太快可能遗漏附件"],
  },
  {
    id: "deep-work",
    category: "work",
    name: "深度工作",
    good: ["专注窗口难得而完整", "复杂问题会在安静中松动"],
    bad: ["频繁通知会切碎思路", "钻得太深可能忘记交付边界"],
  },
  {
    id: "organize-docs",
    category: "work",
    name: "整理文档",
    good: ["散落的信息能重新连成地图", "命名和目录今天格外顺手"],
    bad: ["容易沉迷格式而忘了内容", "旧版本可能被误当成最终稿"],
  },
  {
    id: "tackle-hard-task",
    category: "work",
    name: "推进难题",
    good: ["最卡的一步会出现突破口", "先做小实验就能找到方向"],
    bad: ["硬碰硬只会放大阻力", "缺少上下文时结论容易跑偏"],
  },
  {
    id: "project-retrospective",
    category: "work",
    name: "项目复盘",
    good: ["经验能沉淀成下一次捷径", "诚实面对问题会获得共识"],
    bad: ["复盘可能变成追责大会", "只看结果会错过过程信号"],
  },
  {
    id: "learn-work-tool",
    category: "work",
    name: "学习效率工具",
    good: ["一个快捷操作能省下很多时间", "新流程很快就能形成肌肉记忆"],
    bad: ["折腾工具的时间超过真正工作", "迁移配置时容易丢掉细节"],
  },
  {
    id: "focused-reading",
    category: "learning",
    name: "专注阅读",
    good: ["难懂的段落会突然串起来", "今天适合慢读和做批注"],
    bad: ["注意力会被无关信息带走", "读得太快只留下模糊印象"],
  },
  {
    id: "learn-words",
    category: "learning",
    name: "记单词",
    good: ["联想记忆格外牢固", "零碎时间能积少成多"],
    bad: ["只背列表很快就会遗忘", "相似词义容易互相打架"],
  },
  {
    id: "practice-exercises",
    category: "learning",
    name: "做练习",
    good: ["错误会准确指出知识缺口", "手感会在重复中建立起来"],
    bad: ["追求数量可能忽略理解", "卡在一题上会消耗太久"],
  },
  {
    id: "watch-course",
    category: "learning",
    name: "看课程",
    good: ["老师的一个比喻会点亮概念", "边看边练能立刻形成反馈"],
    bad: ["倍速太高会漏掉关键转折", "收藏课程不等于真正掌握"],
  },
  {
    id: "review-notes",
    category: "learning",
    name: "整理笔记",
    good: ["旧知识会长出新的连接", "一页总结胜过反复翻找"],
    bad: ["美化笔记容易喧宾夺主", "照抄原文难以形成理解"],
  },
  {
    id: "learn-new-skill",
    category: "learning",
    name: "学习新技能",
    good: ["入门门槛没有想象中高", "第一次实践就能得到成就感"],
    bad: ["同时开太多坑会全部浅尝辄止", "跳过基础可能很快碰壁"],
  },
  {
    id: "write-summary",
    category: "learning",
    name: "写学习总结",
    good: ["输出会暴露真正掌握的部分", "结构化表达让记忆更持久"],
    bad: ["为了完整而迟迟不肯动笔", "概念混用会让结论失焦"],
  },
  {
    id: "ask-question",
    category: "learning",
    name: "请教问题",
    good: ["一个好问题能省下几小时", "对方会给出意料之外的视角"],
    bad: ["没说明尝试过程容易得到泛泛回答", "害怕显得无知会错失机会"],
  },
  {
    id: "sleep-early",
    category: "health",
    name: "早点休息",
    good: ["身体会感谢这次及时收工", "明早的清醒值得今晚克制"],
    bad: ["睡前刷屏会让困意溜走", "临时加戏容易拖到深夜"],
  },
  {
    id: "morning-stretch",
    category: "health",
    name: "晨间拉伸",
    good: ["僵硬的肩背会慢慢松开", "温和启动比猛然发力更有效"],
    bad: ["动作太急容易拉伤", "空腹高强度会让身体抗议"],
  },
  {
    id: "strength-training",
    category: "health",
    name: "力量训练",
    good: ["动作控制比重量更有收获", "今天适合稳稳完成计划组数"],
    bad: ["逞强加重量容易破坏姿势", "忽略热身会让关节不高兴"],
  },
  {
    id: "easy-run",
    category: "health",
    name: "轻松慢跑",
    good: ["呼吸和步频会找到舒服节奏", "跑完的心情比配速更漂亮"],
    bad: ["一开始冲太快会后继无力", "身体不适时坚持并非勇敢"],
  },
  {
    id: "balanced-meal",
    category: "health",
    name: "认真吃饭",
    good: ["简单搭配也能吃得满足", "慢一点会更早听见饱腹信号"],
    bad: ["忙到跳餐会影响整天状态", "重口味可能让身体负担加倍"],
  },
  {
    id: "drink-water",
    category: "health",
    name: "补充水分",
    good: ["一杯水能叫醒迟钝的大脑", "规律补水会改善疲惫感"],
    bad: ["等到口渴才想起已经太迟", "用甜饮替代水会适得其反"],
  },
  {
    id: "rest-eyes",
    category: "health",
    name: "让眼睛休息",
    good: ["远眺几分钟就能缓解紧绷", "短暂停屏会换回更长专注"],
    bad: ["连续盯屏容易头昏眼涩", "关灯看手机会让疲劳加倍"],
  },
  {
    id: "health-check",
    category: "health",
    name: "预约体检",
    good: ["提前安排能消除长期惦记", "关注小信号比事后补救轻松"],
    bad: ["拖延不会让担忧自动消失", "只看单项指标容易过度解读"],
  },
  {
    id: "contact-friend",
    category: "social",
    name: "联系朋友",
    good: ["一句近况就能重新接上频道", "久未联系的人可能正好想起你"],
    bad: ["只顾倾诉会忽略对方感受", "深夜突然来电可能让人措手不及"],
  },
  {
    id: "say-thanks",
    category: "social",
    name: "表达感谢",
    good: ["具体的感谢会格外有力量", "真诚会让普通一天变得明亮"],
    bad: ["客套过度反而显得疏远", "只说谢谢却不说明原因容易飘过"],
  },
  {
    id: "listen-carefully",
    category: "social",
    name: "认真倾听",
    good: ["不急着回答会听见真正需求", "一个停顿能给彼此更多空间"],
    bad: ["边听边准备反驳会错过重点", "替别人下结论容易造成误会"],
  },
  {
    id: "team-conversation",
    category: "social",
    name: "团队沟通",
    good: ["把假设说出来就能减少返工", "今天适合对齐边界和期待"],
    bad: ["模糊承诺会留下后续隐患", "在群里争输赢不如回到事实"],
  },
  {
    id: "meet-someone",
    category: "social",
    name: "认识新朋友",
    good: ["共同兴趣会自然打开话题", "保持好奇比刻意表现更迷人"],
    bad: ["过度热情可能让人有压力", "只谈自己会让交流失去来回"],
  },
  {
    id: "family-time",
    category: "social",
    name: "陪伴家人",
    good: ["一顿普通饭也能留下好记忆", "耐心回应会让关系更松弛"],
    bad: ["翻旧账会破坏难得的相处", "用关心包装控制容易引发争执"],
  },
  {
    id: "make-peace",
    category: "social",
    name: "道歉和解",
    good: ["承认具体伤害比解释更有效", "放下防御会让关系重新流动"],
    bad: ["一句但是会抵消前面的歉意", "逼对方立刻原谅并不公平"],
  },
  {
    id: "share-good-news",
    category: "social",
    name: "分享好消息",
    good: ["快乐会因为分享变得更真实", "你的进展也能鼓励身边的人"],
    bad: ["忽略场合容易显得炫耀", "未经同意别替别人公开消息"],
  },
  {
    id: "clean-room",
    category: "home",
    name: "打扫房间",
    good: ["清出桌面也会清出思路", "从一个角落开始就能看到变化"],
    bad: ["一口气全拆开会无处落脚", "忙着收纳可能把东西藏到失踪"],
  },
  {
    id: "organize-wardrobe",
    category: "home",
    name: "整理衣柜",
    good: ["被遗忘的好搭配会重新出现", "留下真正喜欢的会更轻松"],
    bad: ["感情用事会让淘汰计划失败", "没有分类只是在移动杂乱"],
  },
  {
    id: "cook-meal",
    category: "home",
    name: "下厨做饭",
    good: ["手边食材能组合出惊喜", "慢火和耐心会带来好味道"],
    bad: ["边做边改配方容易失控", "忘记计时可能收获焦香过头"],
  },
  {
    id: "small-repair",
    category: "home",
    name: "修理小物",
    good: ["一个小修补能延长很久寿命", "先查结构再动手会很顺利"],
    bad: ["工具不合适容易越修越坏", "涉及电路时不要凭感觉冒险"],
  },
  {
    id: "care-plants",
    category: "home",
    name: "照顾绿植",
    good: ["新芽会回应你的细心", "调整光照比盲目浇水更重要"],
    bad: ["过度关爱也可能淹坏根系", "突然换环境会让植物不适应"],
  },
  {
    id: "do-laundry",
    category: "home",
    name: "洗晒衣物",
    good: ["天气和时间都刚刚好", "分类清洗能让衣物保持状态"],
    bad: ["口袋里的纸巾可能制造雪景", "深浅混洗容易收获意外配色"],
  },
  {
    id: "review-budget",
    category: "home",
    name: "整理预算",
    good: ["看清流向比苛责自己更有用", "一个小调整就能减轻压力"],
    bad: ["冲动消费会伪装成犒劳", "只算大项容易漏掉持续订阅"],
  },
  {
    id: "declutter",
    category: "home",
    name: "断舍离",
    good: ["不再需要的东西会找到新去处", "减少物品也在减少维护成本"],
    bad: ["情绪上头可能扔掉真正需要的", "先买收纳盒并不会自动变整齐"],
  },
  {
    id: "take-walk",
    category: "outdoors",
    name: "出门散步",
    good: ["转过街角会遇见好风景", "缓慢行走能整理混乱心绪"],
    bad: ["只顾看手机会错过脚下台阶", "天气变化可能让计划提前结束"],
  },
  {
    id: "go-hiking",
    category: "outdoors",
    name: "轻量徒步",
    good: ["山风会带走积攒的疲惫", "合适节奏能一路保持好心情"],
    bad: ["低估路程会让返程狼狈", "装备不足时不要挑战陌生路线"],
  },
  {
    id: "ride-bike",
    category: "outdoors",
    name: "骑行",
    good: ["一路绿灯般顺畅", "风和速度会带来久违自由"],
    bad: ["抢快几秒不值得冒险", "出发前忘记检查车况会扫兴"],
  },
  {
    id: "watch-sunset",
    category: "outdoors",
    name: "看日落",
    good: ["天空会送上一场限时展览", "放下相机也能记住这一刻"],
    bad: ["到得太晚只看见最后余光", "只顾找机位会错过真正景色"],
  },
  {
    id: "park-break",
    category: "outdoors",
    name: "公园发呆",
    good: ["什么都不做也是有效恢复", "树影和风声会慢慢降低噪音"],
    bad: ["久坐不动可能让身体更僵", "花粉和蚊虫会突然加入聚会"],
  },
  {
    id: "city-walk",
    category: "outdoors",
    name: "城市漫游",
    good: ["熟悉街区会显出陌生细节", "不设终点反而更容易有发现"],
    bad: ["热门路线可能挤得失去兴致", "走太远才发现返程交通不便"],
  },
  {
    id: "take-photos",
    category: "outdoors",
    name: "外出拍照",
    good: ["光线会替普通场景加上故事", "小心观察就能找到好构图"],
    bad: ["只追参数会失去现场感受", "存储和电量可能关键时刻告急"],
  },
  {
    id: "have-picnic",
    category: "outdoors",
    name: "准备野餐",
    good: ["简单食物也会因为阳光更好吃", "轻装出发能享受真正松弛"],
    bad: ["带得太多会像搬家", "忘看天气可能和阵雨抢地盘"],
  },
  {
    id: "write-something",
    category: "creativity",
    name: "写点东西",
    good: ["第一句话会自然带出下一句", "真实细节比华丽辞藻更有力量"],
    bad: ["等完美开头会一直空白", "反复修改第一段可能走不出去"],
  },
  {
    id: "draw-picture",
    category: "creativity",
    name: "画画",
    good: ["线条会比想象中更有生命", "大胆用色能打开新方向"],
    bad: ["盯着参考图容易失去自己的节奏", "橡皮擦太勤会磨掉勇气"],
  },
  {
    id: "practice-instrument",
    category: "creativity",
    name: "练习乐器",
    good: ["困难小节会逐渐变得顺手", "慢速练习能换来真正稳定"],
    bad: ["只从头弹到尾难以解决问题", "急着提速会把错误一起固定"],
  },
  {
    id: "make-craft",
    category: "creativity",
    name: "做手工",
    good: ["双手会把杂念安静下来", "小小误差也能成为独特细节"],
    bad: ["跳过测量可能在最后一步翻车", "胶水和颜料会占领整张桌子"],
  },
  {
    id: "shoot-video",
    category: "creativity",
    name: "拍视频",
    good: ["自然状态比刻意表演更动人", "提前列镜头能让拍摄很顺畅"],
    bad: ["收音问题会比画面更难补救", "素材太多可能让剪辑无从下手"],
  },
  {
    id: "brainstorm",
    category: "creativity",
    name: "头脑风暴",
    good: ["离谱想法里可能藏着真答案", "先不评判能让思路充分展开"],
    bad: ["过早否定会让讨论迅速降温", "没有收敛标准会一直发散"],
  },
  {
    id: "design-solution",
    category: "creativity",
    name: "设计新方案",
    good: ["限制条件会逼出更聪明的结构", "先画草图能快速发现问题"],
    bad: ["只追求新奇可能牺牲可用性", "没问清需求就容易精致地跑偏"],
  },
  {
    id: "collect-ideas",
    category: "creativity",
    name: "整理灵感",
    good: ["零散片段会组成新的主题", "旧想法今天可能找到合适位置"],
    bad: ["收藏太多会变成信息仓库", "分类过细反而不敢继续记录"],
  },
  {
    id: "watch-anime",
    category: "entertainment",
    name: "追番",
    good: ["这一集会精准击中情绪", "片尾之后仍值得回味"],
    bad: ["再看一集可能直接看到天亮", "随手刷评论容易被提前剧透"],
  },
  {
    id: "watch-movie",
    category: "entertainment",
    name: "看电影",
    good: ["故事会带你离开现实两小时", "今天适合看一部慢慢展开的片子"],
    bad: ["选片时间可能比正片还长", "边看边刷手机会失去完整体验"],
  },
  {
    id: "play-game",
    category: "entertainment",
    name: "玩游戏",
    good: ["手感在线，队友也很默契", "轻松一局就能恢复好心情"],
    bad: ["上头连败会消耗整晚", "把输赢带进聊天容易伤气氛"],
  },
  {
    id: "listen-podcast",
    category: "entertainment",
    name: "听播客",
    good: ["一个陌生观点会打开新窗口", "通勤路上能收获意外陪伴"],
    bad: ["信息密度太高会越听越累", "只听不消化很快就会忘记"],
  },
  {
    id: "build-model",
    category: "entertainment",
    name: "组模型",
    good: ["零件会严丝合缝地归位", "耐心打磨能换来漂亮细节"],
    bad: ["剪错零件会让心跳漏一拍", "赶进度可能留下明显水口"],
  },
  {
    id: "see-performance",
    category: "entertainment",
    name: "看演出",
    good: ["现场氛围会远超录像", "熟悉旋律会变成共同记忆"],
    bad: ["交通和散场可能考验耐心", "只顾拍摄会错过舞台细节"],
  },
  {
    id: "read-comics",
    category: "entertainment",
    name: "看漫画",
    good: ["分镜会把时间悄悄带走", "旧角色会带来熟悉的安慰"],
    bad: ["追到最新话只剩漫长等待", "躺着看太久脖子会抗议"],
  },
  {
    id: "play-with-pet",
    category: "entertainment",
    name: "陪宠物玩",
    good: ["它会用最直接的快乐回应你", "短短互动就能缓解紧张"],
    bad: ["玩得太疯可能收获一地狼藉", "忽略它的边界会被嫌弃"],
  },
] as const satisfies readonly FortuneContentDefinition[];
